### PR TITLE
Added/Enabled properties for hybrid monitoring based on the environme…

### PR DESCRIPTION
**Pull request by coder-159**
Changes made in compile script to enable hybrid monitoring support for PCF.

cc: @nitish29, @VardhanaKulkarni, @awagle

### CODE REVIEW

**Comment by awagle** [comment]
@coder-159 can you confirm that this is expected behavior? I mean that Instrumentation should be turned on by default for on premise apps. If that's the use case changes look okay to me.

**Comment by coder-159** [comment]
Hi @awagle, Thanks for reviewing the code changes.
For on-prem apps, the instrumentation will not enabled by default, it's based on the **HYBRID_AGENT_URL** environment, If the user injects **HYBRID_AGENT_URL** then only instrumentation will be enabled.

**Comment by awagle** [comment]
Akash that's exactly my question: why will we enable instrumentation if
Hybrid Agent URL is provided? Wouldn't this be enabled explicitly since its
an on-prem app instead of a cloud app? Is this part of our requirement?

Regards,

*Aditya Wagle *|  *O*  +91 20 71303035

*TIBCO Software Inc.* |  Pune, India

[image: www.tibco.com] <http://www.tibco.com>

The information transmitted in this electronic communication is intended
only for the person or entity to whom it is addressed and may contain
confidential and/or privileged material. Any review, re-transmission,
dissemination or other use of or taking of any action in reliance upon this
information by persons or entities other than the intended recipient is
prohibited.

**Comment by coder-159** [comment]
Yes, Aditya. Since it's an on-prem app user can explicitly enable the instrumentation based on some other environment variable. [This feature is not there and we will need to provide it].
Currently, from UI functionality for enabling or disabling, the instrumentation is not provided for on-prem apps too, we are assuming that if the user injects HYBRID_AGENT_URL then the user wants to list and monitor on-prem app on tci and internally we are enabling the process instrumentation for on-prem Apps based on an environment variable.

**Pull request merged**
